---
title: "gwas_plotting"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```



```{r}
install.packages("qqman")
install.packages("data.table")

if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("rtracklayer")
BiocManager::install("GenomicFeatures")



library(qqman)
library(data.table)
library(rtracklayer)
library(GenomicRanges)
library(GenomicFeatures)
```


# Load the data

```{r}

### Edit below to the path on your computer
file_path <- "~/Downloads/redlat_GEMMA.txt"

data <- fread(file_path)

# Ensure the column names are as expected
colnames(data) <- c("chr", "rs", "ps", "n_miss", "allele1", "allele0", "af", "beta", "se", "logl_H1", "l_remle", "l_mle", "p_wald", "p_lrt", "p_score")

head(data)

quantile(data$p_lrt)
```


# Overlap with genes to determine if 

```{r}
# Load the GTF file
# Note the below file is available from: https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_46/gencode.v46.annotation.gtf.gz

### Edit the below to point to the local location on your machine
gtf_file_path <- "~/Downloads/gencode.v46.annotation.gtf.gz"
gtf <- rtracklayer::import(gtf_file_path)

# Just take gene body
genes_gr <- subset(gtf, type == "gene")


# Convert numeric chr to standard labels
data$chr_label <- as.character(data$chr)
data$chr_label[data$chr == 23] <- "X"
data$chr_label[data$chr == 24] <- "Y"
data$chr_label <- paste0("chr", data$chr_label)

# Remove any chr not found in GTF (optional)
valid_chrs <- intersect(unique(data$chr_label), seqlevels(gtf))  # e.g., chr1 - chr22, chrX, chrY
data <- data[data$chr_label %in% valid_chrs]

# Now create the SNP GRanges object
snps_gr <- GRanges(
  seqnames = data$chr_label,
  ranges = IRanges(start = data$ps, end = data$ps),
  rs = data$rs
)

# Find overlaps between SNPs and genes
overlaps <- findOverlaps(snps_gr, genes_gr)

# Create a vector to store gene names
data$gene <- NA
data$gene[queryHits(overlaps)] <- genes_gr$gene_name[subjectHits(overlaps)]




head(data$gene)

# what proportion of variants are intergenic?
sum(is.na(data$gene))/nrow(data)
```



```{r}

# Identify significant hits (e.g., p-value < 5e-8)
significant_hits <- data[data$p_lrt < 5e-8]


# Convert p-values to chi-squared statistics (1 degree of freedom)
data$chisq <- qchisq(1 - data$p_lrt, df = 1)

# Remove any infinite or NA values
chisq_clean <- na.omit(data$chisq[is.finite(data$chisq)])

# Calculate lambda (median of observed chi-square / expected median under null, which is 0.456)
lambda_gc <- median(chisq_clean) / qchisq(0.5, df = 1)

# Round for display
lambda_gc_rounded <- round(lambda_gc, 3)





manhattan(data, chr = "chr", bp = "ps", snp = "gene", p = "p_lrt", main = "ReD-Lat AMR AD Standardized AF-0.005",
          annotatePval = 5e-8, annotateTop = TRUE)


manhattan(data, chr = "chr", bp = "ps", snp = "rs", p = "p_lrt", main = paste0("ReD-Lat AMR AD Standardized AF-0.005 (inflation = ", lambda_gc_rounded, ")"),
          annotatePval = 5e-8, annotateTop = TRUE, highlight = significant_hits$rs)
```



